server {
    listen       80;
    server_name  localhost;

    # Lokasi untuk file React di dalam container Nginx
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # Pengalihan SPA ke index.html jika rute tidak ditemukan
        try_files $uri $uri/ /index.html;
    }
}
